name: EasyModeration
main: Rushil13579\EasyModeration\Main
api: 3.0.0
version: 1.1.2
author: Rushil13579
mcpe-protocol: [465]

permissions:
  easymoderation.ipban:
    description: Allows a player to use the ipban command!
  easymoderation.ipunban:
    description: Allows a player to use the ipunban command!
  easymoderation.permban:
    description: Allows a player to use the permban command!
  easymoderation.tempban:
    description: Allows a player to use the tempban command!
  easymoderation.unban:
    description: Allows a player to use the unban command!
  easymoderation.kick:
    description: Allows a player to use the kick command!
  easymoderation.mute:
    description: Allows a player to use the mute command!
  easymoderation.unmute:
    description: Allows a player to use the unmute command!
  easymoderation.mutelist:
    description: Allows a player to use the mutelist command!
  easymoderation.warn:
    description: Allows a player to use the warn command!
  easymoderation.chatcensor.bypass:
    description: Allows a player to bypass chatcensor restrictions!
