# Configuration file for EasyModeration by Rushil13579 | Rushil#2326

# Version [DO NOT TOUCH]
plugin-version: '1.0.0'


# ========== CHAT CENSOR ==========


# Words that will be censored in player chats [can be extends as long as you wish] [keep empty to disable]
# Give permission 'easymoderation.chatcensor.bypass' to bypass it
chat-censor: [ 'fuck', '.com', 'discord.gg' ]


# ========== CHAT INTERVAL ==========


# Interval for chatting [Set to 0 to disable]
# Give permission 'easymoderation.chatinterval.bypass' to bypass it [In seconds]
chat-interval: 2


# ========== WEBHOOKS ==========


# Name of the webhook
webhook-name: 'EasyModeration'


# ===== IP BANS =====


# Recommended to keep ipban & ipunban webhooks in private channels to prevent leaking ips of your players
# Set this to 'enabled' if you want discord posts everytime a player gets ipbanned
ipban-discord-post: disabled

# Webhook url
# Example: https://discord.com/api/webhooks/825780283365523456/o-yWCgL-TyTCxxZ-SHcMZhicVyhWHPk2n4n4PY6QdKrAFm9aUsfRJEXGFe7sAhrTEg9y
ipban-webhook: ''


# Set this to 'enabled' if you want discord posts everytime a player gets ipunbanned
ipunban-discord-post: disabled

# Webhook url
ipunban-webhook: ''


# ===== NORMAL BANS =====


# Set this to 'enabled' if you want discord posts everytime a player gets permbanned
permban-discord-post: disabled

# Webhook url
permban-webhook: ''


# Set this to 'enabled' if you want discord posts everytime a player gets tempbanned
tempban-discord-post: disabled

# Webhook url
tempban-webhook: ''


# Set this to 'enabled' if you want discord posts everytime a player gets unbanned
unban-discord-post: disabled

# Webhook url
unban-webhook: ''


# ===== KICKS =====


# Set this to 'enabled' if you want discord posts everytime a player gets kicked
kick-discord-post: disabled

# Webhook url
kick-webhook: ''


# ===== MUTES =====


# Set this to 'enabled' if you want discord posts everytime a player gets muted
mute-discord-post: disabled

# Webhook url
mute-webhook: ''


# Set this to 'enabled' if you want discord posts everytime a player gets unmuted
unmute-discord-post: disabled

# Webhook url
unmute-webhook: ''


# ===== WARNS =====


# Set this to 'enabled' if you want discord posts everytime a player gets warned
warn-discord-post: disabled

# Webhook url
warn-webhook: ''